// replace with mysql logic to get stadium info
export const stadiums = {
    "Acrisure Stadium": { image: "../images/nfl-stadiums/acrisure-stadium.jpg", name: "Acrisure Stadium", location: "Pittsburgh, PA" },
    "Allegiant Stadium": { image: "../images/nfl-stadiums/allegiant-stadium.jpg", name: "Allegiant Stadium", location: "Las Vegas, NV" },
    "Arrowhead Stadium": { image: "../images/nfl-stadiums/arrowhead-stadium.jpg", name: "Arrowhead Stadium", location: "Kansas City, MO" },
    "AT&T Stadium": { image: "../images/nfl-stadiums/at&t-stadium.jpg", name: "AT&T Stadium", location: "Arlington, TX" },
    "Bank Of America Stadium": { image: "../images/nfl-stadiums/bank-of-america-stadium.jpg", name: "Bank Of America Stadium", location: "Charlotte, NC" },
    "Caesars Superdome": { image: "../images/nfl-stadiums/caesars-superdome.jpg", name: "Caesars Superdome", location: "New Orleans, LA" },
    "Empower Field at Mile High": { image: "../images/nfl-stadiums/empower-field-at-mile-high.jpg", name: "Empower Field at Mile High", location: "Denver, CO" },
    "Everbank Stadium": { image: "../images/nfl-stadiums/everbank-stadium.jpg", name: "Everbank Stadium", location: "Jacksonville, FL" },
    "Ford Field": { image: "../images/nfl-stadiums/ford-field.jpg", name: "Ford Field", location: "Detroit, MI" },
    "Gillette Stadium": { image: "../images/nfl-stadiums/gillette-stadium.jpg", name: "Gillette Stadium", location: "Foxborough, MA" },
    "Hard Rock Stadium": { image: "../images/nfl-stadiums/hard-rock-stadium.jpg", name: "Hard Rock Stadium", location: "Miami Gardens, FL" },
    "Highmark Stadium": { image: "../images/nfl-stadiums/highmark-stadium.jpg", name: "Highmark Stadium", location: "Orchard Park, NY" },
    "Huntington Bank Field": { image: "../images/nfl-stadiums/huntington-bank-field.jpg", name: "Huntington Bank Field", location: "Cleveland, OH" },
    "Lambeau Field": { image: "../images/nfl-stadiums/lambeau-field.jpg", name: "Lambeau Field", location: "Green Bay, WI" },
    "Levi's Stadium": { image: "../images/nfl-stadiums/levis-stadium.jpg", name: "Levi's Stadium", location: "Santa Clara, CA" },
    "Lincoln Financial Field": { image: "../images/nfl-stadiums/lincoln-financial-field.jpg", name: "Lincoln Financial Field", location: "Philadelphia, PA" },
    "Lucas Oil Stadium": { image: "../images/nfl-stadiums/lucas-oil-stadium.jpg", name: "Lucas Oil Stadium", location: "Indianapolis, IN" },
    "Lumen Field": { image: "../images/nfl-stadiums/lumen-field.jpg", name: "Lumen Field", location: "Seattle, WA" },
    "MetLife Stadium (Giants)": { image: "../images/nfl-stadiums/metlife-stadium-giants.jpg", name: "MetLife Stadium (Giants)", location: "East Rutherford, NJ" },
    "MetLife Stadium (Jets)": { image: "../images/nfl-stadiums/metlife-stadium-jets.jpg", name: "MetLife Stadium (Jets)", location: "East Rutherford, NJ" },
    "Mercedes-Benz Stadium": { image: "../images/nfl-stadiums/mercedes-benz-stadium.jpg", name: "Mercedes-Benz Stadium", location: "Atlanta, GA" },
    "M&T Bank Stadium": { image: "../images/nfl-stadiums/m&t-bank-stadium.jpg", name: "M&T Bank Stadium", location: "Baltimore, MD" },
    "Nissan Stadium": { image: "../images/nfl-stadiums/nissan-stadium.jpg", name: "Nissan Stadium", location: "Nashville, TN" },
    "Northwest Stadium": { image: "../images/nfl-stadiums/northwest-stadium.jpg", name: "Northwest Stadium", location: "Unknown" },
    "NRG Stadium": { image: "../images/nfl-stadiums/nrg-stadium.jpg", name: "NRG Stadium", location: "Houston, TX" },
    "Paycor Stadium": { image: "../images/nfl-stadiums/paycor-stadium.jpg", name: "Paycor Stadium", location: "Cincinnati, OH" },
    "Raymond James Stadium": { image: "../images/nfl-stadiums/raymond-james-stadium.jpg", name: "Raymond James Stadium", location: "Tampa, FL" },
    "Sofi Stadium (Chargers)": { image: "../images/nfl-stadiums/sofi-stadium-chargers.jpg", name: "Sofi Stadium (Chargers)", location: "Inglewood, CA" },
    "Sofi Stadium (Rams)": { image: "../images/nfl-stadiums/sofi-stadium-rams.jpg", name: "Sofi Stadium (Rams)", location: "Inglewood, CA" },
    "Soldier Field": { image: "../images/nfl-stadiums/soldier-field.jpg", name: "Soldier Field", location: "Chicago, IL" },
    "State Farm Stadium": { image: "../images/nfl-stadiums/state-farm-stadium.jpg", name: "State Farm Stadium", location: "Glendale, AZ" },
    "US Bank Stadium": { image: "../images/nfl-stadiums/us-bank-stadium.jpg", name: "US Bank Stadium", location: "Minneapolis, MN" },
    "State Farm Arena": { image: "../images/nba-stadiums/state-farm-arena.jpg", name: "State Farm Arena", location: "Atlanta, GA" },
    "TD Garden": { image: "../images/nba-stadiums/td-garden.jpg", name: "TD Garden", location: "Boston, MA" },
    "Barclays Center": { image: "../images/nba-stadiums/barclays-center.jpg", name: "Barclays Center", location: "Brooklyn, NY" },
    "Spectrum Center": { image: "../images/nba-stadiums/spectrum-center.jpg", name: "Spectrum Center", location: "Charlotte, NC" },
    "United Center": { image: "../images/nba-stadiums/united-center.jpg", name: "United Center", location: "Chicago, IL" },
    "Rocket Mortgage Fieldhouse": { image: "../images/nba-stadiums/rocket-mortgage-fieldhouse.jpg", name: "Rocket Mortgage Fieldhouse", location: "Cleveland, OH" },
    "American Airlines Center": { image: "../images/nba-stadiums/american-airlines-center.jpg", name: "American Airlines Center", location: "Dallas, TX" },
    "Ball Arena": { image: "../images/nba-stadiums/ball-arena.jpg", name: "Ball Arena", location: "Denver, CO" },
    "Little Caesars Arena": { image: "../images/nba-stadiums/little-caesars-arena.JPG", name: "Little Caesars Arena", location: "Detroit, MI" },
    "Chase Center": { image: "../images/nba-stadiums/chase-center.jpg", name: "Chase Center", location: "San Francisco, CA" },
    "Toyota Center": { image: "../images/nba-stadiums/toyota-center.jpg", name: "Toyota Center", location: "Houston, TX" },
    "Gainbridge Fieldhouse": { image: "../images/nba-stadiums/gainbridge-fieldhouse.jpg", name: "Gainbridge Fieldhouse", location: "Indianapolis, IN" },
    "Intuit Dome": { image: "../images/nba-stadiums/intuit-dome.jpg", name: "Intuit Dome", location: "Inglewood, CA" },
    "Crypto.com Arena": { image: "../images/nba-stadiums/cryptocom-arena.jpg", name: "Crypto.com Arena", location: "Los Angeles, CA" },
    "FedExForum": { image: "../images/nba-stadiums/fedex-forum.jpg", name: "FedExForum", location: "Memphis, TN" },
    "Kaseya Center": { image: "../images/nba-stadiums/kaseya-center.jpg", name: "Kaseya Center", location: "Miami, FL" },
    "Fiserv Forum": { image: "../images/nba-stadiums/fiserv-forum.jpg", name: "Fiserv Forum", location: "Milwaukee, WI" },
    "Target Center": { image: "../images/nba-stadiums/target-center.jpg", name: "Target Center", location: "Minneapolis, MN" },
    "Smoothie King Center": { image: "../images/nba-stadiums/smoothie-king-center.jpg", name: "Smoothie King Center", location: "New Orleans, LA" },
    "Madison Square Garden": { image: "../images/nba-stadiums/madison-square-garden.jpg", name: "Madison Square Garden", location: "New York, NY" },
    "Paycom Center": { image: "../images/nba-stadiums/paycom-center.jpg", name: "Paycom Center", location: "Oklahoma City, OK" },
    "Kia Center": { image: "../images/nba-stadiums/kia-center.jpg", name: "Kia Center", location: "Orlando, FL" },
    "Wells Fargo Center": { image: "../images/nba-stadiums/wells-fargo-center.jpg", name: "Wells Fargo Center", location: "Philadelphia, PA" },
    "Footprint Center": { image: "../images/nba-stadiums/footprint-center.jpg", name: "Footprint Center", location: "Phoenix, AZ" },
    "Moda Center": { image: "../images/nba-stadiums/moda-center.jpg", name: "Moda Center", location: "Portland, OR" },
    "Golden 1 Center": { image: "../images/nba-stadiums/golden-1-center.jpg", name: "Golden 1 Center", location: "Sacramento, CA" },
    "Frost Bank Center": { image: "../images/nba-stadiums/frost-bank-center.jpg", name: "Frost Bank Center", location: "San Antonio, TX" },
    "Scotiabank Arena": { image: "../images/nba-stadiums/scotiabank-arena.jpg", name: "Scotiabank Arena", location: "Toronto, ON" },
    "Delta Center": { image: "../images/nba-stadiums/delta-center.jpg", name: "Delta Center", location: "Salt Lake City, UT" },
    "Capitol One Arena": { image: "../images/nba-stadiums/capital-one-arena.jpg", name: "Capitol One Arena", location: "Washington, D.C."},
    "Chase Field": { image: "../images/mlb-stadiums/chase-field.jpg", name: "Chase Field", location: "Phoenix, AZ" },
    "Sutter Health Park": { image: "../images/mlb-stadiums/sutter-health-park.jpg", name: "Sutter Health Park", location: "West Sacramento, CA" },
    "Truist Park": { image: "../images/mlb-stadiums/truist-park.jpg", name: "Truist Park", location: "Atlanta, GA" },
    "Oriole Park at Camden Yards": { image: "../images/mlb-stadiums/oriole-park-at-camden-yards.jpg", name: "Oriole Park at Camden Yards", location: "Baltimore, MD" },
    "Fenway Park": { image: "../images/mlb-stadiums/fenway-park.jpg", name: "Fenway Park", location: "Boston, MA" },
    "Wrigley Field": { image: "../images/mlb-stadiums/wrigley-field.jpg", name: "Wrigley Field", location: "Chicago, IL" },
    "Rate Field": { image: "../images/mlb-stadiums/rate-field.jpg", name: "Rate Field", location: "Chicago, IL" },
    "Great American Ballpark": { image: "../images/mlb-stadiums/great-american-ballpark.jpg", name: "Great American Ballpark", location: "Cincinnati, OH" },
    "Progressive Field": { image: "../images/mlb-stadiums/progressive-field.jpg", name: "Progressive Field", location: "Cleveland, OH" },
    "Coors Field": { image: "../images/mlb-stadiums/coors-field.jpg", name: "Coors Field", location: "Denver, CO" },
    "Comerica Park": { image: "../images/mlb-stadiums/comerica-park.jpg", name: "Comerica Park", location: "Detroit, MI" },
    "Daikin Park": { image: "../images/mlb-stadiums/daikin-park.jpg", name: "Daikin Park", location: "Houston, TX" },
    "Kauffman Stadium": { image: "../images/mlb-stadiums/kauffman-stadium.jpg", name: "Kauffman Stadium", location: "Kansas City, MO" },
    "Angel Stadium": { image: "../images/mlb-stadiums/angel-stadium.jpg", name: "Angel Stadium", location: "Anaheim, CA" },
    "Dodger Stadium": { image: "../images/mlb-stadiums/dodger-stadium.jpg", name: "Dodger Stadium", location: "Los Angeles, CA" },
    "loanDepot Park": { image: "../images/mlb-stadiums/loan-depot-park.jpg", name: "loanDepot Park", location: "Miami, FL" },
    "American Family Field": { image: "../images/mlb-stadiums/american-family-field.jpg", name: "American Family Field", location: "Milwaukee, WI" },
    "Target Field": { image: "../images/mlb-stadiums/target-field.jpg", name: "Target Field", location: "Minneapolis, MN" },
    "Citi Field": { image: "../images/mlb-stadiums/citi-field.jpg", name: "Citi Field", location: "Flushing, NY" },
    "Yankee Stadium": { image: "../images/mlb-stadiums/yankee-stadium.jpg", name: "Yankee Stadium", location: "Bronx, NY" },
    "Citizens Bank Park": { image: "../images/mlb-stadiums/citizens-bank-park.jpg", name: "Citizens Bank Park", location: "Philadelphia, PA" },
    "PNC Park": { image: "../images/mlb-stadiums/pnc-park.jpg", name: "PNC Park", location: "Pittsburgh, PA" },
    "Petco Park": { image: "../images/mlb-stadiums/petco-park.jpg", name: "Petco Park", location: "San Diego, CA" },
    "Oracle Park": { image: "../images/mlb-stadiums/oracle-park.jpg", name: "Oracle Park", location: "San Francisco, CA" },
    "T-Mobile Park": { image: "../images/mlb-stadiums/tmobile-park.jpg", name: "T-Mobile Park", location: "Seattle, WA" },
    "Busch Stadium": { image: "../images/mlb-stadiums/busch-stadium.jpg", name: "Busch Stadium", location: "St. Louis, MO" },
    "Tropicana Field": { image: "../images/mlb-stadiums/tropicana-field.jpg", name: "Tropicana Field", location: "St. Petersburg, FL" },
    "Globe Life Field": { image: "../images/mlb-stadiums/globe-life-field.jpg", name: "Globe Life Field", location: "Arlington, TX" },
    "Rogers Centre": { image: "../images/mlb-stadiums/rogers-centre.jpg", name: "Rogers Centre", location: "Toronto, ON" },
    "Nationals Park": { image: "../images/mlb-stadiums/nationals-park.jpg", name: "Nationals Park", location: "Washington, D.C." }
};